#!/bin/sh

set -e

# Download the ZIP file during installation
rm -f /usr/src/sdr-trunk.zip
wget -O /usr/src/sdr-trunk.zip https://github.com/DSheirer/sdrtrunk/releases/download/v0.6.1-beta-1/sdr-trunk-linux-x86_64-v0.6.1-beta-1.zip
unzip -o -d /usr/src /usr/src/sdr-trunk.zip

# Fix the sdrtrunk.desktop file
sed -i "s/^Exec=.*/Exec=\/usr\/src\/sdr-trunk-linux-x86_64-v0.6.1-beta-1\/bin\/sdr-trunk/" /usr/share/applications/sdrtrunk.desktop

#Update the desktop database
update-desktop-database

# Exit successfully
exit 0
